services:

  db-hub-phpmyadmin:
    image: phpmyadmin:latest
    container_name: db-hub-phpmyadmin
    restart: unless-stopped
    ports:
      - "${APP_PORT:-6868}:80"
    environment:
      PMA_ARBITRARY: 0
      PMA_BLOWFISH_SECRET: ${PMA_BLOWFISH_SECRET}
      UPLOAD_LIMIT: 256M
    volumes:
      - db-hub-generated:/etc/phpmyadmin/conf.d:ro
    depends_on:
      - db-hub
    networks:
      - db-hub-net

  db-hub:
    build:
      context: .
      dockerfile: Dockerfile.tunnels
    container_name: db-hub-core
    restart: unless-stopped
    volumes:
      - ${HOME}/.ssh:/root/.ssh:ro
      - ./config/servers.conf:/etc/servers.conf:ro
      - db-hub-generated:/generated
    networks:
      - db-hub-net

volumes:
  db-hub-generated:

networks:
  db-hub-net:
    driver: bridge
