#!/usr/bin/env python3
"""
db-hub entrypoint

Reads /etc/servers.conf, then:
  1. Generates phpMyAdmin PHP config into /generated/custom.inc.php
  2. Opens one autossh tunnel per [section] with type = ssh
  3. Keeps the container alive while tunnels run
"""

import configparser
import os
import signal
import subprocess
import sys
import time

CONF    = "/etc/servers.conf"
OUT_DIR = "/generated"
OUT_PHP = f"{OUT_DIR}/custom.inc.php"

# Docker service name of THIS container (used as phpMyAdmin host for SSH servers)
TUNNEL_HOST = "db-hub"


# ── helpers ────────────────────────────────────────────────────────────────────

def php_str(s: str) -> str:
    """Wrap a value in a PHP single-quoted string literal."""
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def fix_ssh_permissions() -> None:
    ssh_dir = "/root/.ssh"
    if not os.path.isdir(ssh_dir):
        return
    try:
        os.chmod(ssh_dir, 0o700)
    except OSError:
        pass
    for name in os.listdir(ssh_dir):
        try:
            os.chmod(os.path.join(ssh_dir, name), 0o600)
        except OSError:
            pass


# ── phpMyAdmin config generation ───────────────────────────────────────────────

def generate_php(config: configparser.ConfigParser) -> None:
    os.makedirs(OUT_DIR, exist_ok=True)

    lines = [
        "<?php",
        "// Auto-generated by db-hub — do NOT edit by hand.",
        "// Edit config/servers.conf, then run:  make restart",
        "",
        "unset($cfg['Servers']);",
        "$i = 0;",
        "$cfg['ServerDefault'] = 0;",
        "",
    ]

    for section in config.sections():
        s      = config[section]
        stype  = s.get("type", "direct").strip()
        user   = s.get("db_user", "").strip()
        passwd = s.get("db_pass", "").strip()
        auth   = "config" if passwd else "cookie"

        if stype == "ssh":
            host = TUNNEL_HOST
            port = s.get("local_port", "3306").strip()
        else:
            host = s.get("db_host", "localhost").strip()
            port = s.get("db_port", "3306").strip()

        lines += [
            f"// {section}",
            "$i++;",
            f"$cfg['Servers'][$i]['verbose']         = {php_str(section)};",
            f"$cfg['Servers'][$i]['host']            = {php_str(host)};",
            f"$cfg['Servers'][$i]['port']            = {port};",
            f"$cfg['Servers'][$i]['auth_type']       = {php_str(auth)};",
            f"$cfg['Servers'][$i]['AllowNoPassword'] = false;",
        ]
        if user:
            lines.append(f"$cfg['Servers'][$i]['user']            = {php_str(user)};")
        if passwd:
            lines.append(f"$cfg['Servers'][$i]['password']        = {php_str(passwd)};")
        if s.get("compress", "").strip().lower() == "yes":
            lines.append(f"$cfg['Servers'][$i]['compress']        = true;")
        lines.append("")

    with open(OUT_PHP, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(OUT_PHP, 0o644)

    count = len(config.sections())
    print(f"[db-hub] phpMyAdmin config written → {OUT_PHP}  ({count} server(s))")
    for section in config.sections():
        stype = config[section].get("type", "direct").strip()
        print(f"         • {section}  [{stype}]")


# ── SSH tunnel management ──────────────────────────────────────────────────────

def start_tunnel(label: str, s: configparser.SectionProxy) -> "subprocess.Popen | None":
    ssh_host   = s.get("ssh_host",   "").strip()
    ssh_port   = s.get("ssh_port",   "22").strip()
    ssh_user   = s.get("ssh_user",   "").strip()
    ssh_key    = s.get("ssh_key",    "").strip()
    ssh_pass   = s.get("ssh_pass",   "").strip()
    db_host    = s.get("db_host",    "127.0.0.1").strip()
    db_port    = s.get("db_port",    "3306").strip()
    local_port = s.get("local_port", "").strip()

    missing = [k for k, v in [
        ("ssh_host", ssh_host), ("ssh_user", ssh_user), ("local_port", local_port),
    ] if not v]
    if missing:
        print(f"[tunnel] WARN: '{label}' missing fields: {', '.join(missing)} — skipping")
        return None

    if not ssh_key and not ssh_pass:
        print(f"[tunnel] WARN: '{label}' has neither ssh_key nor ssh_pass — skipping")
        return None

    env = {**os.environ, "AUTOSSH_GATETIME": "0"}

    ssh_args = [
        "-F", "/dev/null",   # ignore ~/.ssh/config (avoids permission errors on mounted .ssh)
        "-o", "ServerAliveInterval=30",
        "-o", "ServerAliveCountMax=3",
        "-o", "StrictHostKeyChecking=no",
        "-o", "UserKnownHostsFile=/dev/null",
        "-o", "ExitOnForwardFailure=yes",
        "-p", ssh_port,
        "-L", f"0.0.0.0:{local_port}:{db_host}:{db_port}",
        f"{ssh_user}@{ssh_host}",
    ]

    if ssh_key:
        key_path = f"/root/.ssh/{ssh_key}"
        if not os.path.isfile(key_path):
            print(f"[tunnel] WARN: key not found: {key_path} — skipping '{label}'")
            return None
        cmd = ["autossh", "-M", "0", "-N", "-i", key_path] + ssh_args
        auth_info = f"key={ssh_key}"
    else:
        # Password auth: pass via env var so it never appears in process list
        env["SSHPASS"] = ssh_pass
        extra = ["-o", "PreferredAuthentications=password", "-o", "PasswordAuthentication=yes"]
        cmd = ["sshpass", "-e", "autossh", "-M", "0", "-N"] + extra + ssh_args
        auth_info = "password"

    print(f"[tunnel] {label}: {ssh_user}@{ssh_host}:{ssh_port}  ->  {db_host}:{db_port}  (local :{local_port}, {auth_info})")
    return subprocess.Popen(cmd, env=env)


# ── main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    if not os.path.isfile(CONF):
        print(f"[db-hub] ERROR: {CONF} not found — is servers.conf mounted?")
        signal.pause()
        return

    fix_ssh_permissions()

    config = configparser.ConfigParser(inline_comment_prefixes=(";", "#"))
    config.read(CONF)

    generate_php(config)

    procs: list[subprocess.Popen] = []
    for section in config.sections():
        s = config[section]
        if s.get("type", "direct").strip() == "ssh":
            p = start_tunnel(section, s)
            if p:
                procs.append(p)

    if not procs:
        print("[db-hub] No SSH tunnels configured — container is alive.")
        signal.pause()
        return

    print(f"[db-hub] {len(procs)} tunnel(s) running. Monitoring…")

    def _shutdown(sig: int, _frame: object) -> None:
        print("[db-hub] Shutting down…")
        for p in procs:
            p.terminate()
        sys.exit(0)

    signal.signal(signal.SIGTERM, _shutdown)
    signal.signal(signal.SIGINT, _shutdown)

    while True:
        time.sleep(10)
        for p in procs:
            if p.poll() is not None:
                print(f"[db-hub] Tunnel process (pid {p.pid}) exited — autossh will restart it.")


if __name__ == "__main__":
    main()
